Jpa complex queries
wolox-training/jd-java pull request #17
Opened 2020-05-11 15:03 UTC by joredudiaz

## Summary

- make parameters' repository queries optionals
- Junit test

## Jira Story

https://trello.com/c/6s7twL6I

2020-05-11 17:43 UTC, darkBasic666 requested changes

2020-05-11 17:43 UTC, darkBasic666 commented on src/main/java/wolox/training/repositories/UserRepository.java
> +    User[] findByBirthDateBetweenAndNameContainingIgnoreCase(
Use Optional.

2020-05-11 17:50 UTC, Jimenarosello requested changes

2020-05-11 17:50 UTC, Jimenarosello commented on src/main/java/wolox/training/repositories/BookRepository.java
> +    Book[] findByPublisherAndYearAndGenre(@Param("publisher") String publisher,
Same comment as in the previous PR, why not use lists?

2020-05-13 14:15 UTC, darkBasic666 approved these changes

2020-05-13 15:12 UTC, merged