Creates book model
wolox-training/jd-java pull request #4
Opened 2020-04-15 13:23 UTC by joredudiaz

## Summary

- Creates book model

## Jira Story

https://trello.com/c/bKRxZbSk

2020-04-15 21:01 UTC, Jimenarosello requested changes
just a few tips! 😄

2020-04-15 21:01 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +  public void setId(long id) {
This method should not be included, because you don't want to allow unwanted id changes since it will be generated automatically :)

2020-04-15 21:01 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +public class Book {
We recommend using Lombok to avoid boilerplate code such as getters and setters. Here's some info on how to start using it: https://github.com/Wolox/java-bootstrap/tree/loombok#add-the-lombok-intellij-plugin 
Let us know if you need any help setting it up or using its annotations 😊

2020-04-15 21:01 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +public class Book {
Another good practice is to use our standard of spacing, which is 4 spaces for each tab :) 
you can configure this in intelliJ by using the Save Actions plugin and configuring the Code Style. Here's some info: https://github.com/Wolox/java-bootstrap/tree/master#intellij-save-action-plugin 
let me know if you need any help!

2020-04-16 14:56 UTC, joredudiaz commented on src/main/java/wolox/training/models/Book.java
> +public class Book {
I didn't know lombok 😄 thank you!

2020-04-16 16:35 UTC, Jimenarosello approved these changes
Awesome job! 😄
Just a tip for the future, check out this Lombok annotation: `@Data`, it simplifies some of the annotations in the model :)

2020-04-17 16:08 UTC, darkBasic666 commented
Maybe use javadocs help to clarify code.

2020-04-20 16:42 UTC, darkBasic666 approved these changes

2020-04-20 17:13 UTC, merged